name: Deploy Vite Project to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secrets
        run: |
          echo "Host: ${{ secrets.SERVER_HOST }}"
          echo "Username: ${{ secrets.SERVER_USERNAME }}"
          echo "Key exists: $(if [ -n '${{ secrets.SSH_PRIVATE_KEY }}' ]; then echo 'yes'; else echo 'no'; fi)"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.19.1"

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install Dependencies
        run: pnpm install
        

      - name: build Project
        run: pnpm build

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf /usr/share/nginx/html/deploy-test # 清空旧文件
            mkdir -p /usr/share/nginx/html/deploy-test # 创建目录
      # 将构建文件上传到服务器
      - name: Copy files to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy-test/*"
          target: "/usr/share/nginx/html/deploy-test"
